version: '3'
services:
  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./front-end/softy-pinko-front-end:/var/www/html/softy-pinko-front-end
      - ./front-end/softy-pinko-front-end.conf:/etc/nginx/conf.d/default.conf

  back-end:
    build: 
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "5252:5252"
    volumes:
      - ./back-end:/app