version: '3'
services:
  proxy:
    build: 
      context: ./proxy
      dockerfile: Dockerfile
    image: proxy:latest
    ports:
      - "80:80"
    depends_on:
      - front-end
      - back-end

  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: front-end:latest
    expose:
      - "9000"
    volumes:
      - ./front-end/softy-pinko-front-end:/var/www/html/softy-pinko-front-end
      - ./front-end/softy-pinko-front-end.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - back-end

  back-end:
    build: 
      context: ./back-end
      dockerfile: Dockerfile
    image: back-end:latest
    expose:
      - "5252"
    volumes:
      - ./back-end:/app
  
  
